# Generated by Django 3.0.5 on 2020-05-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenescontenido',
            name='imagen',
            field=models.ImageField(upload_to='contenido/img'),
        ),
    ]
