# Generated by Django 3.0.5 on 2020-04-08 17:38

import habitacion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=500)),
                ('respondido', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_hab', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=6)),
                ('servicios', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reglas',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_comienzo', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[(habitacion.models.EstadosReglas['ACTIVA'], 'Activa'), (
                    habitacion.models.EstadosReglas['INACTIVA'], 'Inactiva')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('estado', models.CharField(choices=[(habitacion.models.EstadosReserva['PENDIENTE'], 'Pendiente'), (
                    habitacion.models.EstadosReserva['CANCELADA'], 'Cancelada'), (habitacion.models.EstadosReserva['APROBADA'], 'Aprobada')], max_length=10)),
                ('comentarios', models.CharField(max_length=150)),
                ('cliente_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='habitacion.Cliente')),
                ('habitacion_id', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='habitacion.Habitacion')),
            ],
        ),
    ]
