# Generated by Django 3.0.5 on 2020-04-21 19:30

import colorfield.fields
from django.db import migrations, models
import habitacion.models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_imageneshabitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_hab',
            field=models.CharField(choices=[(habitacion.models.TiposHabitacion['SIMPLE'], 'Simple'), (habitacion.models.TiposHabitacion['DOBLE'], 'Doble')], max_length=10),
        ),
    ]
