# Generated by Django 3.0.5 on 2020-04-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0004_auto_20200422_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='servicios',
        ),
        migrations.CreateModel(
            name='ServiciosHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=40)),
                ('habitacion', models.ManyToManyField(to='habitacion.Habitacion')),
            ],
        ),
    ]
