# Generated by Django 3.0.5 on 2020-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0005_auto_20200422_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglas',
            name='repetir',
            field=models.BooleanField(default=False),
        ),
    ]
