# Generated by Django 3.0.5 on 2020-04-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0006_reglas_repetir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_hab',
            field=models.CharField(choices=[('Simple', 'SIMPLE'), ('Doble', 'DOBLE')], max_length=10),
        ),
    ]
