# Generated by Django 3.0.5 on 2020-04-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0007_auto_20200422_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglas',
            name='estado',
            field=models.CharField(choices=[('Inactiva', 'INACTIVA'), ('Activa', 'ACTIVA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Aprobada', 'APROBADA'), ('Cancelada', 'CANCELADA')], max_length=10),
        ),
    ]
