# Generated by Django 3.0.5 on 2020-04-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0008_auto_20200422_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.AlterField(
            model_name='imageneshabitacion',
            name='imagen',
            field=models.ImageField(upload_to='habitacion/static/habitacion/img'),
        ),
    ]
