# Generated by Django 3.0.5 on 2020-04-27 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0009_auto_20200424_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='email',
            field=models.EmailField(default='cambiaresteemail@cambio.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='habitacion.Cliente'),
        ),
    ]
