# Generated by Django 3.0.5 on 2020-04-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0010_auto_20200427_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_hab',
            field=models.CharField(choices=[('Simple', 'SIMPLE'), ('Doble', 'DOBLE')], max_length=20),
        ),
    ]
