# Generated by Django 3.0.5 on 2020-04-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0012_auto_20200428_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_hab',
            field=models.CharField(choices=[('Simple', 'SIMPLE'), ('Doble', 'DOBLE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Aprobada', 'APROBADA'), ('Cancelada', 'CANCELADA')], max_length=10),
        ),
    ]
