# Generated by Django 3.0.5 on 2020-04-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0013_auto_20200428_0447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='imageneshabitacion',
            options={'verbose_name_plural': 'Imagenes Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='reglas',
            options={'verbose_name_plural': 'Reglas'},
        ),
        migrations.AlterModelOptions(
            name='reservas',
            options={'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='servicioshabitacion',
            options={'verbose_name_plural': 'Servicios Habitaciones'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(default='relleno', max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(max_length=100),
        ),
    ]
