# Generated by Django 3.0.5 on 2020-04-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0014_auto_20200428_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='comentarios',
            field=models.CharField(default='Sin comentarios', max_length=150),
        ),
    ]
