# Generated by Django 3.0.5 on 2020-05-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0015_auto_20200429_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=40)),
                ('texto', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='reservas',
            name='checkin',
            field=models.DateField(verbose_name='Fecha entrada'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='checkout',
            field=models.DateField(verbose_name='Fecha salida'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'PENDIENTE'), ('Aprobada', 'APROBADA'), ('Cancelada', 'CANCELADA')], max_length=10, verbose_name='Estado de la reserva'),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre de la reserva'),
        ),
        migrations.CreateModel(
            name='ImagenesContenido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='habitacion/static/contenido/img')),
                ('contenido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.Contenido')),
            ],
        ),
    ]
