# Generated by Django 3.0.5 on 2020-05-01 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0016_auto_20200501_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenescontenido',
            name='contenido',
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
        migrations.DeleteModel(
            name='ImagenesContenido',
        ),
    ]
