# Generated by Django 3.0.5 on 2020-05-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0017_auto_20200501_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageneshabitacion',
            name='imagen',
            field=models.ImageField(upload_to='habitacion/img'),
        ),
    ]
